// 由 tools/build_galgod_port.py 自动生成，请勿手改
// 图片索引表：下标即剧本节点里的资源号
export const IMG = [
  "/common/img/b/bg_boy_room_1.png",
  "/common/img/b/bg_boy_room_2.png",
  "/common/img/b/bg_boy_room_3.png",
  "/common/img/b/bg_coffee_1.png",
  "/common/img/b/bg_coffee_3.png",
  "/common/img/b/bg_coffee_4.png",
  "/common/img/b/bg_conference_room_1.png",
  "/common/img/b/bg_corridor_1.png",
  "/common/img/b/bg_girl_room_2.png",
  "/common/img/b/bg_girl_room_4.png",
  "/common/img/b/bg_girl_room_5.png",
  "/common/img/b/bg_hotel_2.png",
  "/common/img/b/bg_hotel_3.png",
  "/common/img/b/bg_ikea_1.png",
  "/common/img/b/bg_living_room_3.png",
  "/common/img/b/bg_office_1.png",
  "/common/img/b/bg_office_2.png",
  "/common/img/b/bg_office_3.png",
  "/common/img/b/bg_sky_3.png",
  "/common/img/b/bg_sky_4.png",
  "/common/img/b/bg_sky_5.png",
  "/common/img/b/bg_street_1.png",
  "/common/img/b/bg_street_2.png",
  "/common/img/b/bg_street_6.png",
  "/common/img/b/jianbian.png",
  "/common/img/s/clothes1_front_skin_black_bare_bewilderment.png",
  "/common/img/s/clothes1_front_skin_black_bare_smile.png",
  "/common/img/s/clothes1_front_skin_black_black_silk_bewilderment.png",
  "/common/img/s/clothes1_front_skin_black_black_silk_smile.png",
  "/common/img/s/clothes1_front_skin_black_white_silk_bewilderment.png",
  "/common/img/s/clothes1_front_skin_black_white_silk_smile.png",
  "/common/img/s/clothes1_front_skin_blush_bare_astonished.png",
  "/common/img/s/clothes1_front_skin_blush_bare_bewilderment.png",
  "/common/img/s/clothes1_front_skin_blush_bare_black.png",
  "/common/img/s/clothes1_front_skin_blush_bare_blush.png",
  "/common/img/s/clothes1_front_skin_blush_bare_cachinnation.png",
  "/common/img/s/clothes1_front_skin_blush_bare_calm.png",
  "/common/img/s/clothes1_front_skin_blush_bare_cat_mouth.png",
  "/common/img/s/clothes1_front_skin_blush_bare_cry.png",
  "/common/img/s/clothes1_front_skin_blush_bare_despise.png",
  "/common/img/s/clothes1_front_skin_blush_bare_eyes_closed.png",
  "/common/img/s/clothes1_front_skin_blush_bare_focus.png",
  "/common/img/s/clothes1_front_skin_blush_bare_laugh_open.png",
  "/common/img/s/clothes1_front_skin_blush_bare_not_good.png",
  "/common/img/s/clothes1_front_skin_blush_bare_pout.png",
  "/common/img/s/clothes1_front_skin_blush_bare_shy.png",
  "/common/img/s/clothes1_front_skin_blush_bare_smile.png",
  "/common/img/s/clothes1_front_skin_blush_bare_smile_close.png",
  "/common/img/s/clothes1_front_skin_blush_bare_surprised_but.png",
  "/common/img/s/clothes1_front_skin_blush_bare_wink.png",
  "/common/img/s/clothes1_front_skin_blush_bare_wrath.png",
  "/common/img/s/clothes1_front_skin_blush_black_silk_astonished.png",
  "/common/img/s/clothes1_front_skin_blush_black_silk_bewilderment.png",
  "/common/img/s/clothes1_front_skin_blush_black_silk_black.png",
  "/common/img/s/clothes1_front_skin_blush_black_silk_blush.png",
  "/common/img/s/clothes1_front_skin_blush_black_silk_cachinnation.png",
  "/common/img/s/clothes1_front_skin_blush_black_silk_calm.png",
  "/common/img/s/clothes1_front_skin_blush_black_silk_cat_mouth.png",
  "/common/img/s/clothes1_front_skin_blush_black_silk_cry.png",
  "/common/img/s/clothes1_front_skin_blush_black_silk_despise.png",
  "/common/img/s/clothes1_front_skin_blush_black_silk_eyes_closed.png",
  "/common/img/s/clothes1_front_skin_blush_black_silk_focus.png",
  "/common/img/s/clothes1_front_skin_blush_black_silk_laugh_open.png",
  "/common/img/s/clothes1_front_skin_blush_black_silk_not_good.png",
  "/common/img/s/clothes1_front_skin_blush_black_silk_pout.png",
  "/common/img/s/clothes1_front_skin_blush_black_silk_shy.png",
  "/common/img/s/clothes1_front_skin_blush_black_silk_smile.png",
  "/common/img/s/clothes1_front_skin_blush_black_silk_smile_close.png",
  "/common/img/s/clothes1_front_skin_blush_black_silk_surprised_but.png",
  "/common/img/s/clothes1_front_skin_blush_black_silk_wink.png",
  "/common/img/s/clothes1_front_skin_blush_black_silk_wrath.png",
  "/common/img/s/clothes1_front_skin_blush_white_silk_astonished.png",
  "/common/img/s/clothes1_front_skin_blush_white_silk_bewilderment.png",
  "/common/img/s/clothes1_front_skin_blush_white_silk_black.png",
  "/common/img/s/clothes1_front_skin_blush_white_silk_blush.png",
  "/common/img/s/clothes1_front_skin_blush_white_silk_cachinnation.png",
  "/common/img/s/clothes1_front_skin_blush_white_silk_calm.png",
  "/common/img/s/clothes1_front_skin_blush_white_silk_cat_mouth.png",
  "/common/img/s/clothes1_front_skin_blush_white_silk_cry.png",
  "/common/img/s/clothes1_front_skin_blush_white_silk_despise.png",
  "/common/img/s/clothes1_front_skin_blush_white_silk_eyes_closed.png",
  "/common/img/s/clothes1_front_skin_blush_white_silk_focus.png",
  "/common/img/s/clothes1_front_skin_blush_white_silk_laugh_open.png",
  "/common/img/s/clothes1_front_skin_blush_white_silk_not_good.png",
  "/common/img/s/clothes1_front_skin_blush_white_silk_pout.png",
  "/common/img/s/clothes1_front_skin_blush_white_silk_shy.png",
  "/common/img/s/clothes1_front_skin_blush_white_silk_smile.png",
  "/common/img/s/clothes1_front_skin_blush_white_silk_smile_close.png",
  "/common/img/s/clothes1_front_skin_blush_white_silk_surprised_but.png",
  "/common/img/s/clothes1_front_skin_blush_white_silk_wink.png",
  "/common/img/s/clothes1_front_skin_blush_white_silk_wrath.png",
  "/common/img/s/clothes1_front_skin_shy_bare_astonished.png",
  "/common/img/s/clothes1_front_skin_shy_bare_blush.png",
  "/common/img/s/clothes1_front_skin_shy_bare_pout.png",
  "/common/img/s/clothes1_front_skin_shy_bare_shy.png",
  "/common/img/s/clothes1_front_skin_shy_bare_smile_close.png",
  "/common/img/s/clothes1_front_skin_shy_black_silk_astonished.png",
  "/common/img/s/clothes1_front_skin_shy_black_silk_blush.png",
  "/common/img/s/clothes1_front_skin_shy_black_silk_pout.png",
  "/common/img/s/clothes1_front_skin_shy_black_silk_shy.png",
  "/common/img/s/clothes1_front_skin_shy_black_silk_smile_close.png",
  "/common/img/s/clothes1_front_skin_shy_white_silk_astonished.png",
  "/common/img/s/clothes1_front_skin_shy_white_silk_blush.png",
  "/common/img/s/clothes1_front_skin_shy_white_silk_pout.png",
  "/common/img/s/clothes1_front_skin_shy_white_silk_shy.png",
  "/common/img/s/clothes1_front_skin_shy_white_silk_smile_close.png",
  "/common/img/s/clothes2_front_skin_black_smile.png",
  "/common/img/s/clothes2_front_skin_blush_astonished.png",
  "/common/img/s/clothes2_front_skin_blush_bewilderment.png",
  "/common/img/s/clothes2_front_skin_blush_calm.png",
  "/common/img/s/clothes2_front_skin_blush_cat_mouth.png",
  "/common/img/s/clothes2_front_skin_blush_despise.png",
  "/common/img/s/clothes2_front_skin_blush_eyes_closed.png",
  "/common/img/s/clothes2_front_skin_blush_focus.png",
  "/common/img/s/clothes2_front_skin_blush_laugh_open.png",
  "/common/img/s/clothes2_front_skin_blush_mask.png",
  "/common/img/s/clothes2_front_skin_blush_smile.png",
  "/common/img/s/clothes2_front_skin_blush_smile_close.png",
  "/common/img/s/clothes2_front_skin_blush_wink.png",
  "/common/img/c/SD10.png",
  "/common/img/c/SD12.png",
  "/common/img/c/SD13.png",
  "/common/img/c/SD14.png",
  "/common/img/c/SD15.png",
  "/common/img/c/SD16.png",
  "/common/img/c/SD17.png",
  "/common/img/c/SD20.png",
  "/common/img/c/SD201.png",
  "/common/img/c/SD21.png",
  "/common/img/c/SD211.png",
  "/common/img/c/cg1.png",
  "/common/img/c/cg2.png",
  "/common/img/c/cg21.png",
  "/common/img/c/cg22.png",
  "/common/img/c/cg30.png",
  "/common/img/c/cg31.png",
  "/common/img/c/cg32.png",
  "/common/img/c/cg40.png",
  "/common/img/c/cg41.png",
  "/common/img/c/cg42.png",
  "/common/img/c/cg500.png",
  "/common/img/c/cg501.png",
  "/common/img/c/cg502.png",
  "/common/img/c/cg510.png",
  "/common/img/c/cg511.png",
  "/common/img/c/cg512.png",
  "/common/img/c/cg520.png",
  "/common/img/c/cg521.png",
  "/common/img/c/cg522.png",
  "/common/img/c/cg530.png",
  "/common/img/c/cg531.png",
  "/common/img/c/cg532.png",
  "/common/img/c/cg600.png",
  "/common/img/c/cg601.png",
  "/common/img/c/cg602.png",
  "/common/img/c/cg610.png",
  "/common/img/c/cg611.png",
  "/common/img/c/cg612.png",
  "/common/img/c/chunbai.png"
]

// 背景代号 -> 图片下标（-1 纯黑 / -2 纯白）
export const BG = {
  "white": -2,
  "black": -1,
  "bg_boy_room_1": 0,
  "bg_boy_room_2": 1,
  "bg_boy_room_3": 2,
  "bg_coffee_1": 3,
  "bg_coffee_3": 4,
  "bg_coffee_4": 5,
  "bg_conference_room_1": 6,
  "bg_corridor_1": 7,
  "bg_girl_room_2": 8,
  "bg_girl_room_4": 9,
  "bg_girl_room_5": 10,
  "bg_hotel_2": 11,
  "bg_hotel_3": 12,
  "bg_ikea_1": 13,
  "bg_living_room_3": 14,
  "bg_office_1": 15,
  "bg_office_2": 16,
  "bg_office_3": 17,
  "bg_sky_3": 18,
  "bg_sky_4": 19,
  "bg_sky_5": 20,
  "bg_street_1": 21,
  "bg_street_2": 22,
  "bg_street_6": 23,
  "jianbian": 24
}

// 立绘 key -> 图片下标
export const SP = {
  "clothes1_front_skin_black_bare_bewilderment": 25,
  "clothes1_front_skin_black_bare_smile": 26,
  "clothes1_front_skin_black_black_silk_bewilderment": 27,
  "clothes1_front_skin_black_black_silk_smile": 28,
  "clothes1_front_skin_black_white_silk_bewilderment": 29,
  "clothes1_front_skin_black_white_silk_smile": 30,
  "clothes1_front_skin_blush_bare_astonished": 31,
  "clothes1_front_skin_blush_bare_bewilderment": 32,
  "clothes1_front_skin_blush_bare_black": 33,
  "clothes1_front_skin_blush_bare_blush": 34,
  "clothes1_front_skin_blush_bare_cachinnation": 35,
  "clothes1_front_skin_blush_bare_calm": 36,
  "clothes1_front_skin_blush_bare_cat_mouth": 37,
  "clothes1_front_skin_blush_bare_cry": 38,
  "clothes1_front_skin_blush_bare_despise": 39,
  "clothes1_front_skin_blush_bare_eyes_closed": 40,
  "clothes1_front_skin_blush_bare_focus": 41,
  "clothes1_front_skin_blush_bare_laugh_open": 42,
  "clothes1_front_skin_blush_bare_not_good": 43,
  "clothes1_front_skin_blush_bare_pout": 44,
  "clothes1_front_skin_blush_bare_shy": 45,
  "clothes1_front_skin_blush_bare_smile": 46,
  "clothes1_front_skin_blush_bare_smile_close": 47,
  "clothes1_front_skin_blush_bare_surprised_but": 48,
  "clothes1_front_skin_blush_bare_wink": 49,
  "clothes1_front_skin_blush_bare_wrath": 50,
  "clothes1_front_skin_blush_black_silk_astonished": 51,
  "clothes1_front_skin_blush_black_silk_bewilderment": 52,
  "clothes1_front_skin_blush_black_silk_black": 53,
  "clothes1_front_skin_blush_black_silk_blush": 54,
  "clothes1_front_skin_blush_black_silk_cachinnation": 55,
  "clothes1_front_skin_blush_black_silk_calm": 56,
  "clothes1_front_skin_blush_black_silk_cat_mouth": 57,
  "clothes1_front_skin_blush_black_silk_cry": 58,
  "clothes1_front_skin_blush_black_silk_despise": 59,
  "clothes1_front_skin_blush_black_silk_eyes_closed": 60,
  "clothes1_front_skin_blush_black_silk_focus": 61,
  "clothes1_front_skin_blush_black_silk_laugh_open": 62,
  "clothes1_front_skin_blush_black_silk_not_good": 63,
  "clothes1_front_skin_blush_black_silk_pout": 64,
  "clothes1_front_skin_blush_black_silk_shy": 65,
  "clothes1_front_skin_blush_black_silk_smile": 66,
  "clothes1_front_skin_blush_black_silk_smile_close": 67,
  "clothes1_front_skin_blush_black_silk_surprised_but": 68,
  "clothes1_front_skin_blush_black_silk_wink": 69,
  "clothes1_front_skin_blush_black_silk_wrath": 70,
  "clothes1_front_skin_blush_white_silk_astonished": 71,
  "clothes1_front_skin_blush_white_silk_bewilderment": 72,
  "clothes1_front_skin_blush_white_silk_black": 73,
  "clothes1_front_skin_blush_white_silk_blush": 74,
  "clothes1_front_skin_blush_white_silk_cachinnation": 75,
  "clothes1_front_skin_blush_white_silk_calm": 76,
  "clothes1_front_skin_blush_white_silk_cat_mouth": 77,
  "clothes1_front_skin_blush_white_silk_cry": 78,
  "clothes1_front_skin_blush_white_silk_despise": 79,
  "clothes1_front_skin_blush_white_silk_eyes_closed": 80,
  "clothes1_front_skin_blush_white_silk_focus": 81,
  "clothes1_front_skin_blush_white_silk_laugh_open": 82,
  "clothes1_front_skin_blush_white_silk_not_good": 83,
  "clothes1_front_skin_blush_white_silk_pout": 84,
  "clothes1_front_skin_blush_white_silk_shy": 85,
  "clothes1_front_skin_blush_white_silk_smile": 86,
  "clothes1_front_skin_blush_white_silk_smile_close": 87,
  "clothes1_front_skin_blush_white_silk_surprised_but": 88,
  "clothes1_front_skin_blush_white_silk_wink": 89,
  "clothes1_front_skin_blush_white_silk_wrath": 90,
  "clothes1_front_skin_shy_bare_astonished": 91,
  "clothes1_front_skin_shy_bare_blush": 92,
  "clothes1_front_skin_shy_bare_pout": 93,
  "clothes1_front_skin_shy_bare_shy": 94,
  "clothes1_front_skin_shy_bare_smile_close": 95,
  "clothes1_front_skin_shy_black_silk_astonished": 96,
  "clothes1_front_skin_shy_black_silk_blush": 97,
  "clothes1_front_skin_shy_black_silk_pout": 98,
  "clothes1_front_skin_shy_black_silk_shy": 99,
  "clothes1_front_skin_shy_black_silk_smile_close": 100,
  "clothes1_front_skin_shy_white_silk_astonished": 101,
  "clothes1_front_skin_shy_white_silk_blush": 102,
  "clothes1_front_skin_shy_white_silk_pout": 103,
  "clothes1_front_skin_shy_white_silk_shy": 104,
  "clothes1_front_skin_shy_white_silk_smile_close": 105,
  "clothes2_front_skin_black_smile": 106,
  "clothes2_front_skin_blush_astonished": 107,
  "clothes2_front_skin_blush_bewilderment": 108,
  "clothes2_front_skin_blush_calm": 109,
  "clothes2_front_skin_blush_cat_mouth": 110,
  "clothes2_front_skin_blush_despise": 111,
  "clothes2_front_skin_blush_eyes_closed": 112,
  "clothes2_front_skin_blush_focus": 113,
  "clothes2_front_skin_blush_laugh_open": 114,
  "clothes2_front_skin_blush_mask": 115,
  "clothes2_front_skin_blush_smile": 116,
  "clothes2_front_skin_blush_smile_close": 117,
  "clothes2_front_skin_blush_wink": 118
}

// 立绘丝袜差分：裸足那版的下标 -> [裸足, 白丝, 黑丝] 三个下标。
// 原作的 syq_adjuster 会按 persistent.stockings_color 注入 feet 属性，
// 移植版在运行时按同一套规则挑一张，见 game.ux 的 feetIdx()。
export const SP_FEET = {
  "25": [25, 29, 27],
  "26": [26, 30, 28],
  "31": [31, 71, 51],
  "32": [32, 72, 52],
  "33": [33, 73, 53],
  "34": [34, 74, 54],
  "35": [35, 75, 55],
  "36": [36, 76, 56],
  "37": [37, 77, 57],
  "38": [38, 78, 58],
  "39": [39, 79, 59],
  "40": [40, 80, 60],
  "41": [41, 81, 61],
  "42": [42, 82, 62],
  "43": [43, 83, 63],
  "44": [44, 84, 64],
  "45": [45, 85, 65],
  "46": [46, 86, 66],
  "47": [47, 87, 67],
  "48": [48, 88, 68],
  "49": [49, 89, 69],
  "50": [50, 90, 70],
  "91": [91, 101, 96],
  "92": [92, 102, 97],
  "93": [93, 103, 98],
  "94": [94, 104, 99],
  "95": [95, 105, 100]
}
